version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8888:8080"
    volumes:
      - /home/staskolodyuk/jenkins_home:/var/jenkins_home
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - "9999:8081"